"use client";

import { useState, useTransition } from "react";
import { saveGalleryCategory, type GalleryActionState } from "@/lib/actions/gallery-admin";
import type { GalleryCategoryInput } from "@/lib/validation/gallery-admin";

const input = "mt-1 min-h-10 w-full rounded-xl border bg-white px-3 py-2 text-sm outline-none focus:border-ocean focus:ring-2 focus:ring-ocean/20";
export function GalleryCategoryEditor({ initialValue, structural, itemCount }: { initialValue: GalleryCategoryInput; structural: boolean; itemCount: number }) {
  const [value, setValue] = useState(initialValue), [pending, startTransition] = useTransition(), [result, setResult] = useState<GalleryActionState>({ ok: false });
  return <div className="rounded-xl border p-4">{result.error ? <p role="alert" className="mb-3 text-sm text-red-700">{result.error}</p> : result.ok ? <p role="status" className="mb-3 text-sm text-deep-ocean">Category saved.</p> : null}<div className="grid gap-3 sm:grid-cols-4"><label className="text-sm">English label<input value={value.en} onChange={(event) => setValue({ ...value, en: event.target.value })} className={input} /></label><label dir="rtl" className="text-sm">Arabic label<input value={value.ar} onChange={(event) => setValue({ ...value, ar: event.target.value })} className={input} /></label><label className="text-sm">Order<input type="number" value={value.displayOrder} onChange={(event) => setValue({ ...value, displayOrder: Number(event.target.value) })} className={input} /></label><label className="text-sm">Status<select value={value.status} onChange={(event) => setValue({ ...value, status: event.target.value as GalleryCategoryInput["status"] })} className={input}><option value="draft">Draft</option><option value="published">Published</option><option value="archived">Archived</option></select></label></div><div className="mt-3 flex flex-wrap items-center gap-3"><button type="button" disabled={pending} onClick={() => startTransition(async () => setResult(await saveGalleryCategory(value)))} className="rounded-full bg-ocean px-4 py-2 text-sm font-semibold text-white disabled:opacity-60">{pending ? "Saving…" : "Save category"}</button><span className="text-xs text-charcoal/60">{structural ? "Structural aggregate category" : `${itemCount} Gallery item(s)`}. Stable key and deletion are intentionally unavailable.</span></div></div>;
}
