"use client";

import { useState, useTransition } from "react";
import { deleteGalleryCategory, saveGalleryCategory, type GalleryActionState } from "@/lib/actions/gallery-admin";
import type { GalleryCategoryInput } from "@/lib/validation/gallery-admin";

const input = "mt-1 min-h-11 w-full rounded-xl border bg-white px-3 py-2 text-sm outline-none focus:border-ocean focus:ring-2 focus:ring-ocean/20";
export function GalleryCategoryEditor({ initialValue, structural = false, itemCount = 0 }: { initialValue: GalleryCategoryInput; structural?: boolean; itemCount?: number }) {
  const [value, setValue] = useState(initialValue), [pending, startTransition] = useTransition(), [result, setResult] = useState<GalleryActionState>({ ok: false });
  const existing = Boolean(initialValue.id);
  return <article className="rounded-xl border bg-white p-4 shadow-soft">{result.error ? <p role="alert" className="mb-3 text-sm text-red-700">{result.error}</p> : result.ok ? <p role="status" className="mb-3 text-sm text-deep-ocean">Category saved.</p> : null}<div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-5"><label className="text-sm font-semibold">Key<input value={value.key} disabled={existing} onChange={(event) => setValue({ ...value, key: event.target.value })} className={input}/></label><label className="text-sm font-semibold">English label<input value={value.en} onChange={(event) => setValue({ ...value, en: event.target.value })} className={input}/></label><label dir="rtl" className="text-sm font-semibold">Arabic label<input value={value.ar} onChange={(event) => setValue({ ...value, ar: event.target.value })} className={input}/></label><label className="text-sm font-semibold">Order<input type="number" min="0" value={value.displayOrder} onChange={(event) => setValue({ ...value, displayOrder: Number(event.target.value) })} className={input}/></label><label className="text-sm font-semibold">Status<select value={value.status} onChange={(event) => setValue({ ...value, status: event.target.value as GalleryCategoryInput["status"] })} className={input}><option value="draft">Draft</option><option value="published">Published</option><option value="archived">Archived</option></select></label></div><div className="mt-4 flex flex-wrap items-center gap-3"><button type="button" disabled={pending} onClick={() => startTransition(async () => setResult(await saveGalleryCategory(value)))} className="min-h-11 rounded-full bg-ocean px-5 text-sm font-semibold text-white disabled:opacity-60">{pending ? "Saving…" : existing ? "Save category" : "Add category"}</button>{existing ? <span className="text-xs text-charcoal/60">{structural ? "Structural aggregate category" : `${itemCount} Gallery item(s)`}. The key stays stable.</span> : null}</div>{existing && !structural ? <form action={deleteGalleryCategory} className="mt-4 border-t pt-4"><input type="hidden" name="id" value={initialValue.id}/><label className="flex items-start gap-2 text-sm"><input type="checkbox" name="confirm" required className="mt-0.5 size-5 accent-ocean"/><span>Delete this category only if no Gallery items use it. Cloudinary assets are unaffected.</span></label><button className="mt-3 text-sm font-semibold text-red-700 underline">Delete category</button></form> : null}</article>;
}
