import Image from "next/image";
import Link from "next/link";

import { GalleryCategoryEditor } from "@/components/admin/gallery/gallery-category-editor";
import { deleteGalleryItem } from "@/lib/actions/gallery-admin";
import { requireAdmin } from "@/lib/auth/admin";
import { getAdminGalleryCategories, getAdminGalleryItems } from "@/lib/gallery/gallery-repository";
import { isSafeGalleryImageReference } from "@/lib/validation/gallery-admin";

const messages: Record<string, string> = { deleted: "Gallery item deleted.", missing: "The Gallery item no longer exists.", "confirmation-required": "Confirm the destructive action before continuing." };
export default async function AdminGalleryPage({ searchParams }: { searchParams: Promise<{ result?: string }> }) {
  await requireAdmin();
  const [items, categories, query] = await Promise.all([getAdminGalleryItems(), getAdminGalleryCategories(), searchParams]);
  return <section aria-labelledby="gallery-title">
    <nav aria-label="Breadcrumb" className="text-sm text-charcoal/60"><Link href="/admin/dashboard" className="underline">Dashboard</Link> / Gallery</nav>
    <div className="mt-5 flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[0.2em] text-ocean">Content management</p><h1 id="gallery-title" className="mt-2 font-display text-4xl font-semibold sm:text-5xl">Gallery</h1><p className="mt-3 max-w-2xl text-charcoal/65">Manage existing image references and independent English and Arabic presentation content.</p></div><Link href="/admin/gallery/new" className="inline-flex min-h-11 items-center rounded-full bg-ocean px-6 font-semibold text-white hover:bg-deep-ocean">Create Gallery item</Link></div>
    {query.result && messages[query.result] ? <p role="status" className="mt-6 rounded-xl border border-ocean/20 bg-ocean/5 p-4 text-sm text-deep-ocean">{messages[query.result]}</p> : null}
    {items.length === 0 ? <div className="mt-8 rounded-2xl border bg-white p-8 text-center"><h2 className="font-display text-2xl font-semibold">No Gallery items yet</h2><p className="mt-2 text-charcoal/65">Create a bilingual draft using an approved existing image reference.</p></div> : <div className="mt-8 space-y-4">{items.map((item) => { const en = item.translations.find((value) => value.locale === "en"), ar = item.translations.find((value) => value.locale === "ar"), category = item.category.translations.find((value) => value.locale === "en"); return <article key={item.id} className="rounded-2xl border bg-white p-5 shadow-soft sm:p-6"><div className="grid gap-5 sm:grid-cols-[9rem_1fr] lg:grid-cols-[9rem_1fr_auto]"><div className="relative aspect-square overflow-hidden rounded-xl border bg-soft-sand">{isSafeGalleryImageReference(item.mediaPath) ? <Image src={item.mediaPath} alt="" fill sizes="144px" className="object-cover" /> : <div className="flex h-full items-center justify-center p-3 text-center text-xs text-red-700">Invalid image reference</div>}</div><div className="min-w-0"><div className="flex flex-wrap gap-2"><span className="rounded-full bg-soft-sand px-3 py-1 text-xs font-bold uppercase">{item.status}</span><span className="rounded-full border px-3 py-1 text-xs font-semibold">{category?.label ?? item.category.key}</span>{item.featured ? <span className="rounded-full border px-3 py-1 text-xs font-semibold">Featured</span> : null}</div><h2 className="mt-3 text-xl font-semibold">{en?.title ?? "Missing English title"}</h2><p dir="rtl" className="mt-1 text-lg">{ar?.title ?? "Missing Arabic title"}</p><dl className="mt-3 grid gap-2 text-sm sm:grid-cols-2"><div><dt className="text-charcoal/55">Display order</dt><dd>{item.displayOrder}</dd></div><div><dt className="text-charcoal/55">Updated</dt><dd>{item.updatedAt.toLocaleDateString("en-GB")}</dd></div></dl></div><Link href={`/admin/gallery/${item.id}/edit`} className="h-fit rounded-full border px-5 py-3 text-center font-semibold">Edit</Link></div><form action={deleteGalleryItem} className="mt-5 border-t pt-4"><input type="hidden" name="id" value={item.id} /><label className="flex items-start gap-3 text-sm"><input type="checkbox" name="confirm" required className="mt-0.5 size-5 accent-ocean" /><span>I understand this permanently deletes the Gallery record and both translations. The referenced image file or remote asset is not deleted.</span></label><button className="mt-3 text-sm font-semibold text-red-700 underline">Delete Gallery item</button></form></article>; })}</div>}
    <section className="mt-12"><h2 className="font-display text-3xl font-semibold">Gallery categories</h2><p className="mt-2 max-w-3xl text-sm text-charcoal/65">Edit existing bilingual labels, order, and visibility. Category keys stay stable; category deletion is unavailable and the database prevents orphaning assigned items.</p><div className="mt-5 space-y-4">{categories.map((category) => { const en = category.translations.find((value) => value.locale === "en")!, ar = category.translations.find((value) => value.locale === "ar")!; return <GalleryCategoryEditor key={category.id} initialValue={{ id: category.id, displayOrder: category.displayOrder, status: category.status, en: en.label, ar: ar.label }} structural={category.key === "all"} itemCount={category._count.items} />; })}</div></section>
  </section>;
}
