"use client";

import { useState, useTransition } from "react";
import { deleteTourPackageType, saveTourPackageType, type TourPackageTypeActionState } from "@/lib/actions/tour-package-type-admin";
import type { TourPackageTypeInput } from "@/lib/validation/tour-package-type-admin";

const control = "mt-1 min-h-11 w-full rounded-xl border bg-white px-3 py-2 text-sm outline-none focus:border-ocean focus:ring-2 focus:ring-ocean/20";
export function TourPackageTypeEditor({ initialValue, tourCount = 0 }: { initialValue: TourPackageTypeInput; tourCount?: number }) {
  const [value, setValue] = useState(initialValue), [pending, startTransition] = useTransition(), [result, setResult] = useState<TourPackageTypeActionState>({ ok: false }); const existing = Boolean(initialValue.originalKey);
  return <article className="rounded-2xl border bg-white p-5 shadow-soft">{result.error ? <div role="alert" className="mb-4 text-sm text-red-700"><p>{result.error}</p>{result.fieldErrors ? <ul className="mt-2 list-disc ps-5">{Object.entries(result.fieldErrors).flatMap(([field, values]) => values.map((message) => <li key={field + message}>{field}: {message}</li>))}</ul> : null}</div> : result.ok ? <p role="status" className="mb-4 text-sm text-deep-ocean">Package type saved.</p> : null}<div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-5"><label className="text-sm font-semibold">Stable key<input value={value.key} disabled={existing} onChange={(event) => setValue({ ...value, key: event.target.value })} className={control}/></label><label className="text-sm font-semibold">English name<input value={value.en} onChange={(event) => setValue({ ...value, en: event.target.value })} className={control}/></label><label dir="rtl" className="text-sm font-semibold">Arabic name<input value={value.ar} onChange={(event) => setValue({ ...value, ar: event.target.value })} className={control}/></label><label className="text-sm font-semibold">Display order<input type="number" min="0" value={value.displayOrder} onChange={(event) => setValue({ ...value, displayOrder: Number(event.target.value) })} className={control}/></label><label className="text-sm font-semibold">Status<select value={value.status} onChange={(event) => setValue({ ...value, status: event.target.value as TourPackageTypeInput["status"] })} className={control}><option value="draft">Inactive draft</option><option value="published">Active</option><option value="archived">Archived</option></select></label></div><div className="mt-4 flex flex-wrap items-center gap-4"><button type="button" disabled={pending} onClick={() => startTransition(async () => setResult(await saveTourPackageType(value)))} className="min-h-11 rounded-full bg-ocean px-5 text-sm font-semibold text-white disabled:opacity-60">{pending ? "Saving…" : existing ? "Save package type" : "Add package type"}</button>{existing ? <span className="text-xs text-charcoal/60">{tourCount} Tour(s). Inactive types remain valid for historical Tours.</span> : null}</div>{existing ? <form action={deleteTourPackageType} className="mt-4 border-t pt-4"><input type="hidden" name="key" value={initialValue.originalKey}/><label className="flex items-start gap-2 text-sm"><input type="checkbox" name="confirm" required className="mt-0.5 size-5 accent-ocean"/><span>Delete only if no Tours reference this type. Otherwise deactivate it.</span></label><button className="mt-3 text-sm font-semibold text-red-700 underline">Delete package type</button></form> : null}</article>;
}
