export const LEGACY_TABLES = [
  "AdminUser",
  "Tour",
  "TourTranslation",
  "TourPricingTier",
  "TourPricingTranslation",
  "TourListItem",
  "TourListItemTranslation",
  "TourItineraryDay",
  "TourItineraryDayTranslation",
  "TourImage",
  "TourImageTranslation",
  "FaqCategory",
  "FaqCategoryTranslation",
  "FaqItem",
  "FaqItemTranslation",
  "ContentPage",
  "ContentPageTranslation",
  "ContentSection",
  "ContentSectionTranslation",
  "ContentItem",
  "ContentItemTranslation",
  "GalleryCategory",
  "GalleryCategoryTranslation",
  "GalleryItem",
  "GalleryItemTranslation",
  "InstagramPost",
  "InstagramPostTranslation",
  "ContactMethod",
  "ContactMethodTranslation",
  "ContactEnquiryType",
  "ContactEnquiryTypeTranslation",
  "SiteSetting",
  "SiteSettingTranslation",
  "SocialLink",
  "SocialLinkTranslation",
  "SeoMetadata",
  "CloudinaryAsset",
  "Review",
  "BookingRequest",
  "ContactRequest",
] as const;

export type LegacyTable = (typeof LEGACY_TABLES)[number];

export const MIGRATION_GROUPS: ReadonlyArray<{
  name: string;
  tables: readonly LegacyTable[];
}> = [
  { name: "administrators", tables: ["AdminUser"] },
  {
    name: "tours",
    tables: [
      "Tour",
      "TourTranslation",
      "TourPricingTier",
      "TourPricingTranslation",
      "TourListItem",
      "TourListItemTranslation",
      "TourItineraryDay",
      "TourItineraryDayTranslation",
      "TourImage",
      "TourImageTranslation",
    ],
  },
  {
    name: "faq",
    tables: [
      "FaqCategory",
      "FaqCategoryTranslation",
      "FaqItem",
      "FaqItemTranslation",
    ],
  },
  {
    name: "content",
    tables: [
      "ContentPage",
      "ContentPageTranslation",
      "ContentSection",
      "ContentSectionTranslation",
      "ContentItem",
      "ContentItemTranslation",
    ],
  },
  {
    name: "gallery",
    tables: [
      "GalleryCategory",
      "GalleryCategoryTranslation",
      "GalleryItem",
      "GalleryItemTranslation",
      "InstagramPost",
      "InstagramPostTranslation",
    ],
  },
  {
    name: "contact-configuration",
    tables: [
      "ContactMethod",
      "ContactMethodTranslation",
      "ContactEnquiryType",
      "ContactEnquiryTypeTranslation",
    ],
  },
  {
    name: "site-configuration",
    tables: [
      "SiteSetting",
      "SiteSettingTranslation",
      "SocialLink",
      "SocialLinkTranslation",
      "SeoMetadata",
    ],
  },
  { name: "cloudinary-assets", tables: ["CloudinaryAsset"] },
  { name: "reviews", tables: ["Review"] },
  { name: "requests", tables: ["BookingRequest", "ContactRequest"] },
];

export const TABLE_PRIMARY_KEYS: Record<LegacyTable, string> = {
  AdminUser: "id",
  Tour: "id",
  TourTranslation: "id",
  TourPricingTier: "id",
  TourPricingTranslation: "id",
  TourListItem: "id",
  TourListItemTranslation: "id",
  TourItineraryDay: "id",
  TourItineraryDayTranslation: "id",
  TourImage: "id",
  TourImageTranslation: "id",
  FaqCategory: "id",
  FaqCategoryTranslation: "id",
  FaqItem: "id",
  FaqItemTranslation: "id",
  ContentPage: "id",
  ContentPageTranslation: "id",
  ContentSection: "id",
  ContentSectionTranslation: "id",
  ContentItem: "id",
  ContentItemTranslation: "id",
  GalleryCategory: "id",
  GalleryCategoryTranslation: "id",
  GalleryItem: "id",
  GalleryItemTranslation: "id",
  InstagramPost: "id",
  InstagramPostTranslation: "id",
  ContactMethod: "id",
  ContactMethodTranslation: "id",
  ContactEnquiryType: "id",
  ContactEnquiryTypeTranslation: "id",
  SiteSetting: "id",
  SiteSettingTranslation: "id",
  SocialLink: "id",
  SocialLinkTranslation: "id",
  SeoMetadata: "id",
  CloudinaryAsset: "publicId",
  Review: "id",
  BookingRequest: "id",
  ContactRequest: "id",
};

