import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { MessageCircle } from "lucide-react";
import { FAQCategorySection } from "@/components/faq/faq-category-section";
import { Container } from "@/components/layout/container";
import { Section } from "@/components/layout/section";
import { siteSettingsPlaceholder } from "@/config/site-settings";
import { isLocale } from "@/i18n/config";
import { getFAQContent } from "@/i18n/content/faq";
import { languageAlternates, localizedHref } from "@/i18n/routing";
import { getFaqSeo, getPublishedFaqContent } from "@/lib/content/faq-repository";

export async function generateMetadata({params}:PageProps<"/[locale]/faq">):Promise<Metadata>{const{locale}=await params;if(!isLocale(locale))notFound();const data=await getFaqSeo(locale);if(!data)notFound();return{title:data.title,description:data.description,alternates:{languages:languageAlternates("/faq")},openGraph:{title:data.title,description:data.description,type:"website",url:`/${locale}/faq`,images:data.imagePath?[{url:data.imagePath}]:undefined}}}
export default async function FAQPage({params}:PageProps<"/[locale]/faq">){const{locale}=await params;if(!isLocale(locale))notFound();const ui=getFAQContent(locale),managed=await getPublishedFaqContent(locale),data={...ui,...managed};const categories=[...data.categories].sort((a,b)=>a.displayOrder-b.displayOrder),items=[...data.items].filter(i=>i.question&&i.answer.length).sort((a,b)=>a.displayOrder-b.displayOrder);const json={"@context":"https://schema.org","@type":"FAQPage",mainEntity:items.map(item=>({"@type":"Question",name:item.question,acceptedAnswer:{"@type":"Answer",text:item.answer.flatMap(block=>block.type==="list"?block.items:[block.text]).join("\n")}}))};return <main><script type="application/ld+json">{JSON.stringify(json).replace(/</g,"\\u003c")}</script><section className="bg-charcoal pb-16 pt-36 text-white sm:pb-20 sm:pt-40"><Container className="max-w-5xl"><p className="mb-5 text-xs font-bold uppercase tracking-[0.24em] text-ocean-light">{data.hero.eyebrow}</p><h1 className="max-w-4xl font-display text-5xl font-semibold leading-[0.98] sm:text-6xl lg:text-7xl">{data.hero.title}</h1><p className="mt-6 max-w-3xl text-base leading-7 text-white/75 sm:text-lg sm:leading-8">{data.hero.description}</p></Container></section><Section className="bg-soft-sand"><Container className="max-w-5xl"><nav aria-label={data.contact.categoryAria} className="mb-16 sm:mb-20"><ul className="flex flex-wrap gap-2">{categories.map(c=><li key={c.key}><Link href={`#faq-${c.key}`} className="inline-flex min-h-11 items-center rounded-full border border-warm-line bg-white px-4 py-2 text-sm font-semibold text-charcoal hover:border-ocean hover:text-ocean focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ocean">{c.label}</Link></li>)}</ul></nav><div className="space-y-16 sm:space-y-20">{categories.map(c=><FAQCategorySection key={c.key} category={c} items={items.filter(i=>i.category===c.key)}/>)}</div><aside className="mt-20 rounded-[2rem] bg-palm px-6 py-8 text-white shadow-soft sm:flex sm:items-center sm:justify-between sm:gap-10 sm:px-10 sm:py-10"><div><h2 className="font-display text-3xl font-semibold sm:text-4xl">{data.contact.title}</h2><p className="mt-3 max-w-2xl leading-7 text-white/75">{data.contact.description}</p></div><div className="mt-6 flex flex-col gap-3 sm:mt-0 sm:shrink-0 sm:flex-row"><Link href={localizedHref(locale,"/contact")} className="inline-flex min-h-12 items-center justify-center rounded-full bg-white px-6 text-sm font-bold text-charcoal">{data.contact.contactLabel}</Link><a href={siteSettingsPlaceholder.contact.whatsappUrl} target="_blank" rel="noopener noreferrer" aria-label={data.contact.whatsappAria} className="inline-flex min-h-12 items-center justify-center gap-2 rounded-full border border-white/35 px-6 text-sm font-bold text-white"><MessageCircle aria-hidden="true" className="size-4"/>{data.contact.whatsappLabel}</a></div></aside></Container></Section></main>}
