"use client";

import { useState, useTransition } from "react";
import { saveContactMethod, saveEnquiryType, type ContentActionState } from "@/lib/actions/content-admin";
import type { ContactMethodInput, EnquiryTypeInput } from "@/lib/validation/content-admin";

const input="mt-1 min-h-10 w-full rounded-xl border bg-white px-3 py-2 text-sm outline-none focus:border-ocean focus:ring-2 focus:ring-ocean/20";
const statuses=["draft","published","archived"] as const;
export function ContactMethodEditor({value}:{value:ContactMethodInput}){const[data,setData]=useState(value),[pending,start]=useTransition(),[result,setResult]=useState<ContentActionState>({ok:false}); const update=(key:keyof ContactMethodInput,value:unknown)=>setData(current=>({...current,[key]:value})); return <div className="rounded-xl border p-4">{result.error?<p role="alert" className="mb-3 text-sm text-red-700">{result.error}</p>:result.ok?<p role="status" className="mb-3 text-sm text-deep-ocean">Saved.</p>:null}<div className="grid gap-3 sm:grid-cols-3"><label className="text-sm">Type<select value={data.type} onChange={e=>update("type",e.target.value)} className={input}>{["email","phone","whatsapp","location","social"].map(v=><option key={v}>{v}</option>)}</select></label><label className="text-sm">Public value<input value={data.value} onChange={e=>update("value",e.target.value)} className={input}/></label><label className="text-sm">Safe href<input value={data.href} onChange={e=>update("href",e.target.value)} className={input}/></label><label className="text-sm">Order<input type="number" value={data.displayOrder} onChange={e=>update("displayOrder",Number(e.target.value))} className={input}/></label><label className="text-sm">Status<select value={data.status} onChange={e=>update("status",e.target.value)} className={input}>{statuses.map(v=><option key={v}>{v}</option>)}</select></label><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={data.external} onChange={e=>update("external",e.target.checked)}/>Open externally</label></div><div className="mt-3 grid gap-3 sm:grid-cols-2"><label className="text-sm">English label<input value={data.en.label} onChange={e=>setData({...data,en:{...data.en,label:e.target.value}})} className={input}/></label><label dir="rtl" className="text-sm">Arabic label<input value={data.ar.label} onChange={e=>setData({...data,ar:{...data.ar,label:e.target.value}})} className={input}/></label><label className="text-sm">English description<input value={data.en.description} onChange={e=>setData({...data,en:{...data.en,description:e.target.value}})} className={input}/></label><label dir="rtl" className="text-sm">Arabic description<input value={data.ar.description} onChange={e=>setData({...data,ar:{...data.ar,description:e.target.value}})} className={input}/></label></div><button type="button" disabled={pending} onClick={()=>start(async()=>setResult(await saveContactMethod(data)))} className="mt-4 rounded-full bg-ocean px-4 py-2 text-sm font-semibold text-white disabled:opacity-60">{pending?"Saving…":"Save method"}</button></div>}
export function EnquiryTypeEditor({value}:{value:EnquiryTypeInput}){const[data,setData]=useState(value),[pending,start]=useTransition(),[result,setResult]=useState<ContentActionState>({ok:false});return <div className="rounded-xl border p-4">{result.error?<p role="alert" className="mb-3 text-sm text-red-700">{result.error}</p>:result.ok?<p role="status" className="mb-3 text-sm text-deep-ocean">Saved.</p>:null}<div className="grid gap-3 sm:grid-cols-5"><label className="text-sm">Stable value<input value={data.value} onChange={e=>setData({...data,value:e.target.value})} className={input}/></label><label className="text-sm">Order<input type="number" value={data.displayOrder} onChange={e=>setData({...data,displayOrder:Number(e.target.value)})} className={input}/></label><label className="text-sm">Status<select value={data.status} onChange={e=>setData({...data,status:e.target.value as typeof data.status})} className={input}>{statuses.map(v=><option key={v}>{v}</option>)}</select></label><label className="text-sm">English label<input value={data.en} onChange={e=>setData({...data,en:e.target.value})} className={input}/></label><label dir="rtl" className="text-sm">Arabic label<input value={data.ar} onChange={e=>setData({...data,ar:e.target.value})} className={input}/></label></div><button type="button" disabled={pending} onClick={()=>start(async()=>setResult(await saveEnquiryType(data)))} className="mt-4 rounded-full bg-ocean px-4 py-2 text-sm font-semibold text-white disabled:opacity-60">{pending?"Saving…":"Save enquiry type"}</button></div>}
