"use client";

import Link from "next/link";
import { useRouter } from "next/navigation";
import { useState, useTransition } from "react";
import { useFieldArray, useForm } from "react-hook-form";

import { saveFaq, type ContentActionState } from "@/lib/actions/content-admin";
import type { FaqInput } from "@/lib/validation/content-admin";

const control = "mt-2 min-h-11 w-full rounded-xl border bg-white px-3 py-2 outline-none focus:border-ocean focus:ring-2 focus:ring-ocean/20";
export const emptyFaq: FaqInput = { categoryId: "", displayOrder: 0, status: "draft", en: { question: "", answer: [{ type: "paragraph", text: "" }] }, ar: { question: "", answer: [{ type: "paragraph", text: "" }] } };

export function FaqForm({ initialValue, categories }: { initialValue: FaqInput; categories: { id: string; label: string }[] }) {
  const router = useRouter(), [pending, startTransition] = useTransition(), [result, setResult] = useState<ContentActionState>({ ok: false });
  const form = useForm<FaqInput>({ defaultValues: initialValue });
  const en = useFieldArray({ control: form.control, name: "en.answer" as "en.answer" | "ar.answer" }), ar = useFieldArray({ control: form.control, name: "ar.answer" as "en.answer" | "ar.answer" });
  const submit = form.handleSubmit((values) => startTransition(async () => { const response = await saveFaq(values); setResult(response); if (response.ok) { router.push(`/admin/faq/${response.id}/edit?saved=1`); router.refresh(); } }));
  const language = (locale: "en" | "ar", fields: typeof en.fields, append: typeof en.append, remove: typeof en.remove) => <fieldset dir={locale === "ar" ? "rtl" : "ltr"} className="rounded-2xl border bg-white p-5 shadow-soft sm:p-7"><legend className="px-2 font-display text-2xl font-semibold">{locale === "en" ? "English content" : "Arabic content"}</legend><label className="block font-semibold">Question<input {...form.register(`${locale}.question`)} className={control}/></label><div className="mt-6 space-y-4">{fields.map((field,index)=><div key={field.id} className="rounded-xl border bg-soft-sand/40 p-4"><div className="grid gap-3 sm:grid-cols-[12rem_1fr]"><label className="text-sm font-semibold">Block type<select {...form.register(`${locale}.answer.${index}.type`)} className={control}><option value="paragraph">Paragraph</option><option value="list">List</option><option value="subheading">Subheading</option><option value="quote">Quote</option></select></label><label className="text-sm font-semibold">{form.watch(`${locale}.answer.${index}.type`) === "list" ? "List items (one per line)" : "Text"}<textarea value={(() => { const value=form.watch(`${locale}.answer.${index}`); return value.type === "list" ? value.items.join("\n") : value.text; })()} onChange={(event)=>{const type=form.getValues(`${locale}.answer.${index}.type`); form.setValue(`${locale}.answer.${index}`, type === "list" ? {type:"list",items:event.target.value.split("\n")} : {type,text:event.target.value} as never)}} className={`${control} min-h-28`}/></label></div><button type="button" onClick={()=>remove(index)} className="mt-3 text-sm font-semibold text-red-700 underline">Remove block</button></div>)}</div><button type="button" onClick={()=>append({type:"paragraph",text:""})} className="mt-4 rounded-full border px-4 py-2 text-sm font-semibold">Add answer block</button></fieldset>;
  return <form onSubmit={submit} className="space-y-7" noValidate>{result.error?<div role="alert" className="rounded-xl border border-red-300 bg-red-50 p-4 text-sm text-red-800"><p>{result.error}</p>{result.fieldErrors?<ul className="mt-2 list-disc ps-5">{Object.entries(result.fieldErrors).flatMap(([key,values])=>values.map(value=><li key={key+value}>{key}: {value}</li>))}</ul>:null}</div>:null}<fieldset className="rounded-2xl border bg-white p-5 shadow-soft sm:p-7"><legend className="px-2 font-display text-2xl font-semibold">Publication</legend><div className="grid gap-5 sm:grid-cols-3"><label className="font-semibold">Category<select {...form.register("categoryId")} className={control}>{categories.map(category=><option key={category.id} value={category.id}>{category.label}</option>)}</select></label><label className="font-semibold">Display order<input type="number" {...form.register("displayOrder",{valueAsNumber:true})} className={control}/></label><label className="font-semibold">Status<select {...form.register("status")} className={control}><option value="draft">Draft</option><option value="published">Published</option><option value="archived">Archived</option></select></label></div></fieldset>{language("en",en.fields,en.append,en.remove)}{language("ar",ar.fields,ar.append,ar.remove)}<div className="sticky bottom-4 flex flex-wrap justify-end gap-3 rounded-2xl border bg-white/95 p-4 shadow-soft"><Link href="/admin/faq" className="inline-flex min-h-11 items-center rounded-full border px-5 font-semibold">Cancel</Link><button disabled={pending} className="rounded-full bg-ocean px-6 font-semibold text-white disabled:opacity-60">{pending?"Saving…":"Save FAQ"}</button></div></form>;
}
